<a href="https://colab.research.google.com/github/Amart85/100-Days-Of-ML-Code/blob/master/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# General Notes
* A tensor is a multi-dimensional array. For eg. A batch of 100 color images of size 32x32 can be represented as a (224, 224, 3, 100) tensor where
  * 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
  * 3 is the number of colour channels of the image (red, green blue).
  * 100 is the batch size (the number of images a neural network sees at any one time)
* Tensors can run on GPUs & TPUs. Numpy arrays can't. 
- Data types -> [See image](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)
    - Scalar → a single number.
    - Vector → an array of numbers
    - Matrix → a 2-d array of numbers
    - Tensor → an n-dimensional array of numbers.

In [ ]:
# RUN THIS BEFORE YOU RUN ANY OTHER CODE BLOCK
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# declare a constant scalar
scalar = tf.constant(7)
print(scalar)
# check the number of dimensions
scalar.ndim

tf.Tensor(7, shape=(), dtype=int32)


0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [ ]:
# Create a matrix
matrix = tf.constant([
    [10,7],
    [7,10]
])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [ ]:
# Custom data type matrix
new_matrix = tf.constant([
    [10.,7.],
    [3.,2.],
    [8.,9.]
],dtype=tf.float16)
print(new_matrix)
print(new_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
2


In [ ]:
# Create a tensor
tensor = tf.constant([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])
print(tensor)
print("Dimension",tensor.ndim)

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)
Dimension 3


In [ ]:
# Creating variable tensors.
variable_tensor = tf.Variable([
    [
        [1,2,3]
    ],
    [
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])
print(variable_tensor)
# print(variable_tensor.ndim)

<tf.Variable 'Variable:0' shape=(3, 1, 3) dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>


In [ ]:
# Creating random tensors
# Tensors of arbitary size with random numbers. 
seed = tf.random.Generator.from_seed(42)
random_1 = seed.normal(shape=(3,2))
print(random_1)
random_2 = seed.uniform(shape=(3,2))
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7647915  0.03845465]
 [0.8506975  0.20781887]
 [0.711869   0.8843919 ]], shape=(3, 2), dtype=float32)


In [ ]:
# Generating Tensors of Zeros and Ones
zeros = tf.zeros(shape=(3,3))
print(zeros)
ones = tf.ones(shape=(4,4))
print(ones)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [ ]:
# Converting Numpy arrays into tensors
import numpy as np
numpy_arr = np.arange(1,25,dtype=np.int32)
print("Numpy arr",numpy_arr)
tensor = tf.constant(numpy_arr,shape=[2,4,3])
print("Tensor",tensor)

Numpy arr [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Tensor tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


In [ ]:
# Getting shape, size and dimensions of a tensor
rank4_tensor = tf.zeros([2,3,4,5])
print(rank4_tensor)
print("Size",tf.size(rank4_tensor))
print("Shape",rank4_tensor.shape)
print("Dimensions",rank4_tensor.ndim)
print("Shape of first dimension",rank4_tensor.shape[0])

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)
Size tf.Tensor(120, shape=(), dtype=int32)
Shape (2, 3, 4, 5)
Dimensions 4
Shape of first dimension 2


In [ ]:
# Basic operations
basic_tensor = tf.constant([[10,7],[2,7]])
# Addition
print(basic_tensor+10)
# Subtraction
print(basic_tensor - 100)
# Multiplication
print(basic_tensor * 10)
# Division
print(basic_tensor / 10)

tf.Tensor(
[[20 17]
 [12 17]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-90 -93]
 [-98 -93]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 20  70]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.2 0.7]], shape=(2, 2), dtype=float64)


In [ ]:
# Matrix Multiplication
# Note: for matrix multiplications, inner dimensions should match.
# eg. (3, 5) * (3, 5) won't work but (3, 5) * (5, 3) will work
# Final result will have the shape of the outer dimensions. eg. (5, 3) * (3, 5) -> (5, 5)
# @ is the symbol used for matrix multiplication in Python. tf.matmul() is recommended for tensors. 
tensor_011 = tf.constant([[2,2],[4,4]])
tensor_012 = tf.constant([[2,2],[4,4]])
print(tf.matmul(tensor_011,tensor_012))

tf.Tensor(
[[12 12]
 [24 24]], shape=(2, 2), dtype=int32)


In [ ]:
# Reshape and Transpose
tensor_013 = tf.constant([[1,2],[3,4]])

# Reshape a tensor to a different dimension
print(tf.reshape(tensor_013,[4,1]))

# Transpose
print(tf.transpose(tensor_013))

tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Aggregate values and operations
tensor_014 = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype='float32')

print(tf.reduce_min(tensor_014)) # Min
print(tf.reduce_max(tensor_014)) # Max
print(tf.reduce_mean(tensor_014)) # Mean
print(tf.reduce_sum(tensor_014)) # Sum
print(tf.math.reduce_std(tensor_014)) # Standard Deviation
print(tf.math.reduce_variance(tensor_014)) # Variance
print(tf.square(tensor_014)) # Square of every number
print(tf.sqrt(tensor_014)) # Square root of every number
print(tf.math.log(tensor_014)) # Log of every number

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(45.0, shape=(), dtype=float32)
tf.Tensor(2.5819888, shape=(), dtype=float32)
tf.Tensor(6.6666665, shape=(), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]
 [2.6457512 2.828427  3.       ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]], shape=(3, 3), dtype=float32)


## One hot encoding
* Used to encode data to make it simpler for algorithmns to learn. 
* eg. a 2d tensor of RGB colours can be represented as [[1,0,0],[0,1,0],[0,0,1]]. Translates to [R, G, B].
![alt text](https://miro.medium.com/max/1400/1*ggtP4a5YaRx6l09KQaYOnw.png "Title")

In [ ]:
# one hot encoding
tensor_015 = [0, 1, 2, 3]
tf.one_hot(tensor_015,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Print available devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]